name: Semgrep Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: semgrep/semgrep-action@v2
        with:
          publish_token: ${{ secrets.SEMGREP_APP_TOKEN }}
